### ISSUE TITLE
some way for improving visual

### ISSUE THREAD

**Issue by pcadeot** [Molkobain/itop-bubble-caselogs#2]
here are some possible improvements when styling those bubbles :
(let's say when using the extension there were some violent reactions)

example here : https://pasteboard.co/JMVcKfz.png

```
#whitening content background (because when typing in some content the background is light with rich editor so that way it maintains readability of rich and mixed cut&past content)
#inner rounding
#thickness adjustment

.mbc-tcbe-content {
    color: black;
    background: #fAfAfA;
    padding: 14px;
    margin: -3px;
    border-radius: 5px;
}

# outer rounding
.molkobain-bubble-caselogs .mbc-thread .mbc-thread-content .mbc-tcb-entries {
    border-radius: 5px;
}

# user color (aka "identité du demandeur"): #457b3d4f
# agent color (aka "intervenant en charge du dossier"): #ffffff54
# other agent variant (aka "autre intervenant A") : #acb4d2c7
# other agent variant (aka "autre intervenant B") : #bda1a1a8
```
> then, quick n dirty experiment to group all agents to the right side i mixed in div.mbc-tc-block classes mbc-tc-block-color-x` and `mbc-tc-block-me to inherit "me" right aligned and "color-x" color definitions - except for the ::before element that links the bubble to the user avatar

**Comment by Molkobain** [comment]
Hello @pcadeot ,

Thanks for the feedback! Indeed at the time this extension was developed (5 years ago), the colors / style were ok, but now it's way more flashy 😅

Actually, for the re-integration of this into iTop 3.0.0 we did something more neutral in the portal : https://pasteboard.co/JMZ8Ucc.png
And something completely different for the backoffice : https://pasteboard.co/JMZ9zdY.png

I might make a last version of this extension to put the neutral colors on it for people which will stay on iTop 2.7 for a while, but i don't know if there are many people in that case.

Anyway, thank you for the ides!

Take care,
Guillaume

**Comment by pcadeot** [comment]
Hello Guillaume,

What is the most important is light background inside bubble (in that sense, the portal view in 3.0.0 is still not satisfying) because we heavily use ckeditor which is presented to the user with a white background... white background which is not embedded into the log when displayed into the bubble :)

So I really like what you did for the back office, and there would be many people interested in this style available for 2.7 as it is used for our academy support and a few others... for portal and backoffice..

Pierre
If you want we cat exchange via pierre.cadeot at ac-reunion dot fr ;)

**Comment by Molkobain** [comment]
Regarding the backoffice style, unfortunately it won't be available for 2.7 as it is part of a global re-design of the backoffice not this extension.

I'll keep in mind and share with the Combodo's team that a dark background might not be a good idea for the bubbles in the portal. I think @steffunky also raised this point.

Thanks!

**Comment by Molkobain** [comment]
PS: A new version of this extension integrating smooth colors will be released in the coming weeks :)

**Comment by Molkobain** [comment]
Hello @pcadeot ,

Just released a new version (https://github.com/Molkobain/itop-bubble-caselogs/releases/tag/v1.4.0) with only white bubbles, way more neutral / modern as the old orange ones 😁

Kept the sharp corners though as it's matching the 2.7 portal/backoffice UI, round corners will be part of the upcoming iTop 3.0.

Thanks again for the feedback!
Guillaume

**Comment by pcadeot** [comment]
Thanks a lot Guillaume,

I forwarded all the informations to the people in charge, I'm no longer tasked with going further forward about it :)

Regards,
Pierre
